#!/bin/bash

pid=`ps -o pid,command | grep $1 | grep -v grep | grep -v tail | grep -v kill | sed -e 's/^[ \t]*//' | cut -d ' ' -f 1`
word_count=`echo $pid | wc -w`
if [ $word_count == 1 ]
then
    echo "kill $pid"
    kill $pid
    exit 0
else
    if [ $word_count == 0 ] ; then
	    echo "There are no matches"
        exit 0
	else
	    echo "There are multiple matches: $pid"
        exit 1
	fi
fi
